### ISSUE TITLE
Trying to pull player season stats...

### ISSUE THREAD

**Issue by olliefu** [jlcarmic/node-stattleship#13]
Hey All - I am trying to pull the player season stats. Is this right?

stattleship.player_season_stats('baseball', 'mlb', params).then(function(player_season_stats) {
    player_season_stats.forEach(function(element, index, array) {
        //console.log(element.name);
        console.log(element.batting_average);
    });
});

**Comment by jlcarmic** [comment]
The `player_season_stats` isn't currently supported.
