### ISSUE TITLE
MLB games not working

### ISSUE THREAD

**Issue by Jimmy-Hernandez** [jlcarmic/node-stattleship#8]
The following function used to work, but now is not returning the array of MLB games. The exact same function currently works for NFL (replacing season_id with 'nfl-2016-2017' and 'baseball' with 'football')

var getAllMlbGames = function () {
var _alMlbGames=[];
    var params = {
        season_id: "mlb-2016"
    };
    stattleship.games('baseball', 'mlb', params).then(function (games) {
        _allMlbGames = games;
    });
};

**Comment by dthyresson** [comment]
I double checked that the API is returning all MLB games via curl:

```
curl -X "GET" "https://api.stattleship.com/baseball/mlb/games?season_id=mlb-2016" \
    -H "Accept: application/vnd.stattleship.com; version=1" \
    -H "Authorization: Token token=TOKEN" \
    -H "Content-Type: application/json"
```

With 2933 games

```
HTTP/1.1 200 OK
Server: Cowboy
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: public, no-cache
Link: <https://api.stattleship.com/baseball/mlb/games?page=74&season_id=mlb-2016>; rel="last", <https://api.stattleship.com/baseball/mlb/games?page=2&season_id=mlb-2016>; rel="next"
Total: 2933
Per-Page: 40
```

As I'll likely look to update this for https://github.com/jlcarmic/node-stattleship/issues/9 I'll have check to see that the MLB example works.

**Comment by jlcarmic** [comment]
@ClassicCreation can you confirm that David's update (v 1.1.1) fixes this issue?

**Comment by Jimmy-Hernandez** [comment]
Confirmed thanks so much guys!
