### ISSUE TITLE
Need to Change URI to api.stattleship.com

### ISSUE THREAD

**Issue by dthyresson** [jlcarmic/node-stattleship#9]
We'll be dedicating the "api" subdomain to the API and using "www" for marketing and other uses.

This means will need to change the url to:

`api.stattleship.com`

The nice thing about this is we'll now offer better edge cached responses.

The `www` is going to be sunsetted next week.

**Comment by Jimmy-Hernandez** [comment]
Thank you! Unfortunately it looks like the www subdomain was flipped off before the node wrapper was updated. Do you have any idea on the timeline of making this change?

**Comment by dthyresson** [comment]
@jlcarmic can you review https://github.com/jlcarmic/node-stattleship/pull/10 and test the change I made to use the new subdomain -- and merge if ok?

Thanks

**Comment by jlcarmic** [comment]
Thanks for taking care of this! Will do an `npm publish` as soon as I'm back at my machine.

**Comment by jlcarmic** [comment]
Closed by https://github.com/jlcarmic/node-stattleship/pull/10
